import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

def mandelbrot(x, y, max_iter):
    c = x + 1j * y
    z = np.zeros_like(c, dtype=np.complex128)
    m = np.zeros(c.shape, dtype=int)
    
    for i in range(max_iter):
        mask = np.abs(z) < 2
        z[mask] = z[mask] ** 2 + c[mask]
        m[mask & (np.abs(z) >= 2)] = i
    return m

image_width = 1200
image_height = 800
max_iterations = 256

x = np.linspace(-2.5, 1.0, image_width)
y = np.linspace(-1.5, 1.5, image_height)
X, Y = np.meshgrid(x, y)

print('Computing Mandelbrot set...')
M = mandelbrot(X, Y, max_iterations)

colors = [
    (0.0, 0.0, 0.0),
    (0.1, 0.0, 0.2),
    (0.3, 0.0, 0.5),
    (0.5, 0.0, 0.8),
    (0.8, 0.2, 1.0),
    (1.0, 0.4, 0.8),
    (1.0, 0.7, 0.4),
    (1.0, 1.0, 0.2),
    (0.5, 1.0, 0.3),
    (0.0, 0.8, 0.8),
    (0.2, 0.4, 1.0),
    (0.5, 0.0, 0.5),
    (0.0, 0.0, 0.0)
]
cmap = plt.cm.colors.LinearSegmentedColormap.from_list("mandelbrot", colors)

plt.figure(figsize=(16, 10))
plt.imshow(M, extent=[-2.5, 1.0, -1.5, 1.5], cmap=cmap, origin='lower', interpolation='bilinear')
plt.title('Mandelbrot Fractal - Generated by OmniCoder-9B on AMD RX590', fontsize=16, fontweight='bold')
plt.xlabel('Real Axis', fontsize=12)
plt.ylabel('Imaginary Axis', fontsize=12)
plt.colorbar(label='Iterations', shrink=0.8)
plt.tight_layout()

output_path = 'C:/Users/frede/Documents/GitHub/llama.cpp/mandelbrot_fractal.png'
plt.savefig(output_path, dpi=200, bbox_inches='tight', facecolor='black')
print(f'Saved to {output_path}')